### ISSUE TITLE
Intergrate HeliPort

### ISSUE THREAD

**Issue by zxystd** [OpenIntelWireless/itlwm#135]
Intergrate HeliPort

**Comment by Stevemoretz** [comment]
Hi thanks for all the efforts,After this is done will we get complete ui interaction?Or it's just a some basic integration only?

**Comment by williambj1** [comment]
What's your definition/expectation of "complete" and "basic"?

**Comment by Stevemoretz** [comment]
Well, I mean can we get a working ui for connecting and disconnecting turning on and off wifi?Or it's just some preparation only and we get these things later?because in your repo for heliport you have written that it's on its first development stages yet.So I was wondering what will we get when this task by zxystd will be done.

**Comment by williambj1** [comment]
I'd encourage you to build HeliPort and test it yourself, so far "a working ui for connecting and disconnecting turning on and off wifi" is already implemented.
