### ISSUE TITLE
AC 9560 - Speed (Download/Upload) and Location services app (Siri, Maps, Weathers,...)

### ISSUE THREAD

**Issue by t3s8r8** [OpenIntelWireless/itlwm#194]
Hi devs, thanks a lot for your outstanding job to Hackintosher community with such an Intel kexts project !

Now it seems every Intel AC wifi cards can perfom on macOS (Hackintosh) but I don't know if another Intel AC can use location services since network references detect them as Wifi instead Ethenet ? But currently AC 9560 still be detected as Ethernet, not Wifi, so problem is how can I use location services on Siri, Weather, Maps,... ? I think we need to have MAC address (spoof for instance) here ? or any ways to make it works ?

Beside the download and upload speed: Download never go further 30 mbps and upload never go further 20 mbps, hope soon there's a change.

Thanks again for your contributions.

**Comment by 1Revenger1** [comment]
itlwm reports itself as an Ethernet NIC to macOS, rather than wifi. This means that Find My does not work, since it relies on Wifi data (like what networks are around you). This likely means that other location services don't work as well. A MAC address spoof has nothing to do with it.

Right now, this only works supports 802.11n, which is only 20MHz wide. Though, I do think that slightly faster speeds should be possible even with it only being 802.11n.
