### ISSUE TITLE
How to use iPhone Hotspot with ITLWM

### ISSUE THREAD

**Issue by BigEmperor26** [OpenIntelWireless/itlwm#749]
If you are using ITLWM you cannot enable iPhone hotspot by pressing the Wi-Fi icon. However if you have the iPhone on the hotspot page, you can go to settings/network/join another network and manually enter the SSID and password of your hotspot. It will not fail.

I just needed to share this (useful?) info.

**Comment by usr-sse2** [comment]
You can just (disable Bluetooth on the notebook OR disable Bluetooth on iPhone) AND turn on hotspot in iPhone Settings or Control Center. Either of these actions will make iPhone appear not as Instant Hotspot (that shows the charge level) but as a regular Wi-Fi network, so that Mac will not try to turn on the hotspot on the iPhone but just connect to it.

**Comment by williambj1** [comment]
I've updated the docs to include this guide. Thanks for the contribution.

**Comment by brucewayne229** [comment]
What about using AirportItlwm ? Its the same ? I cant connect with my personal hotspot. I click on it but after few minutes it said " personal hotspot could not be enable " im using intel AC 7265
