### ISSUE TITLE
[Coding] Difference between Monterey and Ventura

### ISSUE THREAD

**Issue by dreamwhite** [OpenIntelWireless/itlwm#824]
I was checking diffs between [Monterey](https://github.com/OpenIntelWireless/itlwm/blob/master/AirportItlwm/AirportItlwm-Monterey-Info.plist) and [Ventura](https://github.com/OpenIntelWireless/itlwm/blob/master/AirportItlwm/AirportItlwm-Ventura-Info.plist) Info.plist but there's no difference.
At this point I have a question: why are there two duplicate files?
What's their purpose?

**Comment by zxystd** [comment]
They are no differences. Because the product is created when the Ventura is in beta stage, I don't know whether they will change the IO80211Family dependency after RC or stable Ventura version, so I make a new info.plist.

**Comment by williambj1** [comment]
> what changes between Info.plist and Monterey Info.plist is the OSBundleLibraries
This is needed since the library was **renamed** to IO80211Legacy.

> Isn't there any possible way of creating a unique kext without having to differentiate the versions
Unless you don't link against any IO80211 libraries and use Lilu to hook every symbol in the library, which is not practical at all.
Apple changes the data structures and symbol names for IO80211 in every macOS version, the library name itself, written in the plist, means nothing. A bit of C knowledge would tell you how headers, macros and linking work.
The public API for IOEthernet is unified across all modern versions of macOS, therefore a single binary is enough.
